name: Node.js Docker CI/CD

on:
  push:
    branches: 
      - Kanchanop6509650229-patch-2
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calc_workflows:latest

      # Step 3: Test Docker Image
  test-docker-image:
    needs: build-docker
    runs-on: ubuntu-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Run Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/calc_workflows:latest
          docker run -d --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/calc_workflows:latest

      - name: Run Automated Tests in Docker Container
        run: |
          docker exec test-container npm test 

      - name: Clean Up Docker Container
        run: |
          docker stop test-container
          docker rm test-container
